// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOZnRKPoV3H4GhlfqWE4Ck7hG1yhxc4-o',
    appId: '1:797225435979:web:fea9ff37393f1d6223dece',
    messagingSenderId: '797225435979',
    projectId: 'majinbuu-mood-clone',
    authDomain: 'majinbuu-mood-clone.firebaseapp.com',
    storageBucket: 'majinbuu-mood-clone.appspot.com',
    measurementId: 'G-2SBJ78C4S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM4E2-2SIWWRA6aPDUsisaxFV2RFQk8IY',
    appId: '1:797225435979:android:031d00333a4b5c5123dece',
    messagingSenderId: '797225435979',
    projectId: 'majinbuu-mood-clone',
    storageBucket: 'majinbuu-mood-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUnVihYvbuX_U6HMWk0j5he7VDdN-v61s',
    appId: '1:797225435979:ios:cebc1421842b524f23dece',
    messagingSenderId: '797225435979',
    projectId: 'majinbuu-mood-clone',
    storageBucket: 'majinbuu-mood-clone.appspot.com',
    iosBundleId: 'com.example.snsClone',
  );
}
