// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9iwHGdLxknqalLf0A3gswrjXkrI8M-fo',
    appId: '1:91433447554:web:da153d872a8e6a352bc49b',
    messagingSenderId: '91433447554',
    projectId: 'majinbuu-sns-clone',
    authDomain: 'majinbuu-sns-clone.firebaseapp.com',
    storageBucket: 'majinbuu-sns-clone.appspot.com',
    measurementId: 'G-TKDTY5LGCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCppn4Y7nsM2UIK9-dvjmX60xcOlPt5chU',
    appId: '1:91433447554:android:9275876bb71008902bc49b',
    messagingSenderId: '91433447554',
    projectId: 'majinbuu-sns-clone',
    storageBucket: 'majinbuu-sns-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpZCR6fKS07kCdPMuef0RghIN-0ajEFpA',
    appId: '1:91433447554:ios:538957e7e1716f522bc49b',
    messagingSenderId: '91433447554',
    projectId: 'majinbuu-sns-clone',
    storageBucket: 'majinbuu-sns-clone.appspot.com',
    iosBundleId: 'com.example.snsClone',
  );
}
